### ISSUE TITLE
Modify how to use.

### ISSUE THREAD

**Issue by samtsai15** [igorskyflyer/npm-encode-entities#2]
I can not run this example from README.

```
const encoder = require('encode-entities')

console.log(encoder.encode('<strong>')) // outputs '&#60;strong&#62;'
```

So I tried others way , it works.

```
const Encoder = require('encode-entities'); 
const encoder = new Encoder(); 

console.log(encoder.encode('<strong>')); // &#60;strong&#62;

```

**Comment by igorskyflyer** [comment]
@samtsai15, yes, you are correct, thank you for pointing this out. I will update the documentation accordingly.
Thank you for trying out my NPM package.

**Comment by igorskyflyer** [comment]
The issue has been fixed, thank you @samtsai15 (EarthFeng).
